engines:
  pep8:
    enabled: true
    checks:
      W291:
        enabled: false
      W293:
        enabled: false
      E402:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  fixme:
      enabled: true
      exclude_paths:
        - "*"
        - "!src/osisoftpy/**"
        - "src/osisoftpy/legacy/"
ratings:
  paths:
  - "!*"
  - "src/osisoftpy/**"
  - "!src/osisoftpy/legacy/"
  - "**.py"
exclude_paths:
- "*"
- "!src/osisoftpy/**"
- "src/osisoftpy/legacy/"