language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
before_install:
  - pip install --upgrade pytest
install:
  - pip install -q -e .
script:
  - python -m pytest