language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
before_install:
  - pip install --upgrade pytest
  - pip install codecov
  - pip install pytest-cov
install:
  - pip install -q -e .
script:
  - python -m pytest --cov
after_success:
  - codecov
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - dstcontrols:SUPzxzw8n9xyevY5kUkajRAm#pge
    template:
      - "%{repository} build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) %{result} in %{elapsed_time}"
      - "%{author}: %{message}"