language: python

branches:
  only:
    - master
python:
  - 2.7
  # - 3.3
  # - 3.4
  # - 3.5
  # - 3.6
  # - nightly
before_install:
  - pip install --upgrade pytest
  - pip install codecov
  - pip install pytest-cov
  - pip install codeclimate-test-reporter
install:
  - pip install -q -e .
script:
  - python -m pytest --cov
after_success:
  - codecov
  - codeclimate-test-reporter
notifications:
  slack:
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
    rooms:
      - dstcontrols:SUPzxzw8n9xyevY5kUkajRAm#pge
    template:
      - "Build <%{build_url}|#%{build_number}> by %{author} %{result} in %{elapsed_time}."
      - "(<%{compare_url}|%{commit}>) %{commit_message} - %{author}"
