version: 2.0.15.{build}
environment:
  CODECLIMATE_REPO_TOKEN:
    secure: h882+EhxvohqsIHhmdCFTluKjh2EgljVUiZOS47JnNthXtwKp/08v+v22UPnBK2zfZyagmudqUphAiY14qx4vFhYmnTzQj0AFMknZU5aiJ0=
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
#    - PYTHON: "C:\\Python27"
#    - PYTHON: "C:\\Python33"
#    - PYTHON: "C:\\Python34"
#    - PYTHON: "C:\\Python35"
#    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
#    - PYTHON: "C:\\Python33-x64"
#    - PYTHON: "C:\\Python34-x64"
#    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

init:
  - ps: GWMI win32_logicaldisk | FT DeviceId, `
        @{n="Size";e={[math]::Round($_.Size/1GB,2)}},`
        @{n="Free";e={[math]::Round($_.FreeSpace/1GB,2)}}
  - "%PYTHON%\\python.exe -V"
  - "%PYTHON%\\python.exe -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""
  - "%PYTHON%\\python.exe -m pip install six"
  - "%PYTHON%\\python.exe -m pip install setuptools -U -I"
  - "%PYTHON%\\python.exe -m pip install wheel -U -I"
  - "%PYTHON%\\python.exe -m pip install pytest"
  - "%PYTHON%\\python.exe -m pip install pytest-cov"
  - "%PYTHON%\\python.exe -m pip install --editable ."

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest --cov"

after_test:
  - "%PYTHON%\\python.exe -m pip download --requirement requirements.txt --dest dist\\deps"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - ps: Get-ChildItem .\dist\deps | Where-Object { $_.Name -match "(cp[\d]+)-(cp[\d]+m)-(win.+?)(?=\.whl)" }
  - ps: $python_tag = $matches[1]; $abi_tag = $matches[2]; $platform_tag = $matches[3];
  - ps: $osisoftpy_wheel = Get-ChildItem .\dist | Where-Object { $_.Name -match "(osisoftpy-[\d]+.?[\d]+.?[\d]+.?)-.+(?=\.whl)" }
  - ps: $package_build = $matches[1]
  - ps: $artifact_name = -join (($package_build, $python_tag, $abi_tag, $platform_tag -join '-'), '.zip')
  - ps: Remove-Item .\dist\osisoftpy*$platform_tag.zip*
  - ps: 7z a -tzip dist\$artifact_name '.\dist\*' -aoa '-i!*.whl' '-x!*.zip' '-x!*.tmp'
  - ps: "ls dist -recurse"
  - ps: GWMI win32_logicaldisk | FT DeviceId, `
        @{n="Size";e={[math]::Round($_.Size/1GB,2)}},`
        @{n="Free";e={[math]::Round($_.FreeSpace/1GB,2)}}


# I give up getting coverage report submission from appveyor.
#on_success:
#  - "%PYTHON%\\python.exe -m pip install codeclimate-test-reporter"
#  - "%PYTHON%\\python.exe -m pip install codecov"
#  - "%PYTHON%\\python.exe -m coverage xml --ignore-errors -o coverage.xml"
#  - "codeclimate-test-reporter  --debug"
#  - "%PYTHON%\\python.exe -m codecov -X gcov"

notifications:
  - provider: Slack
    incoming_webhook:
      secure: cD/h53d0l9UlqM9TRgv7uxYp6v+tIIy65S+7cOKeCsPWdeW1nZXPHvuPPJgdfrTBabDjuhQdT/tQol4vKZrehxNnaqf6ST/sNCCJgrTPp14=
    channel: '#pge'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

artifacts:
  - path: dist\*
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: sZ10WMoOk9Amwd/0/VjtaRRVPML0g4zr6LngcKdQXwJQV7JA4vOCd3d/J8zLz4Cz
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

branches:
  only:
    - master
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/
