version: 1.0.{build}
environment:
  CODECLIMATE_REPO_TOKEN:
    secure: h882+EhxvohqsIHhmdCFTluKjh2EgljVUiZOS47JnNthXtwKp/08v+v22UPnBK2zfZyagmudqUphAiY14qx4vFhYmnTzQj0AFMknZU5aiJ0=
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

init:
  - "%PYTHON%\\python.exe -V"
  - "%PYTHON%\\python.exe -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install --editable ."
  - "%PYTHON%\\python.exe -m pip install --upgrade pytest"
  - "%PYTHON%\\python.exe -m pip install --upgrade pytest-cov"
  - "%PYTHON%\\python.exe -m pip install wheel"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest --cov"

after_test:
  - "%PYTHON%\\python.exe -m pip download --requirement requirements.txt --dest dist\\deps"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - ps: "ls dist"


# I give up getting coverage report submission from appveyor.
#on_success:
#  - "%PYTHON%\\python.exe -m pip install codeclimate-test-reporter"
#  - "%PYTHON%\\python.exe -m pip install codecov"
#  - "%PYTHON%\\python.exe -m coverage xml --ignore-errors -o coverage.xml"
#  - "codeclimate-test-reporter  --debug"
#  - "%PYTHON%\\python.exe -m codecov -X gcov"
#  - TODO: upload the content of dist/*.whl to a public wheelhouse

notifications:
  - provider: Slack
    incoming_webhook:
      secure: cD/h53d0l9UlqM9TRgv7uxYp6v+tIIy65S+7cOKeCsPWdeW1nZXPHvuPPJgdfrTBabDjuhQdT/tQol4vKZrehxNnaqf6ST/sNCCJgrTPp14=
    channel: '#pge'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

artifacts:
  - path: dist\*
