name: venv-conda-dev
dependencies:
  - python=3.6   # or 2.7
  - ipython
  - numpy
  - pandas
  - pip:
    - wrapt             # via pip-tools, python-dateutil
    - coverage
    - bumpversion
    - pytest
    - py                # via pytest
    - pytest-cov
    - howdoi
    - pygments          # via howdoi
    - pyquery           # via howdoi
    - cssselect         # via pyquery
    - lxml              # via pyquery
    - requests-cache    # via howdoi
    - pip-tools
    - click             # via pip-tools
    - first             # via pip-tools
